### ISSUE TITLE
check filestore to bluestore migration is setup properly

### ISSUE THREAD

**Issue by pponnuvel** [canonical/hotsos#115]
In a user environment, we noticed that:
- bluestore is set to false 
-  journal device is left configured from a previous filestore deployment.

These could be checked by hotsos. Possibly anything else that's left over from filestore.

**Comment by dosaboy** [comment]
So first we need to check ceph.conf to see if the options set by the charm [1] reflect bluestore=true or false. Then we need a way to look at the osd itself and determine if it is actually filestore or bluestore to correlate the two together and decide whether need to raise an issue.

[1] https://github.com/openstack/charm-ceph-osd/blob/e5ac333a973c1ce4353f6a5dbaee9aad66bf4561/templates/ceph.conf#L47

**Comment by dosaboy** [comment]
We now has a CephBase.bluestore_enabled property [1] so should make it easier to implement this check.

[1] https://github.com/dosaboy/hotsos/blob/84497c3aa8e65ca55d8b7d7ec0a316fb2d0f0328/core/plugins/storage.py#L300
