### ISSUE TITLE
warn if any task has been blocked for more than 120 seconds in kern.log 

### ISSUE THREAD

**Issue by nkshirsagar** [canonical/hotsos#198]
Warn in hotsos if any task has been blocked for longer than hung_task_timeout.

Entire call traces might be too long or bulky to print in hotsos, but hotsos could output something like "XXX process has been blocked for more than 120 seconds" if seen in the latest boot? (we should ignore these messages in older boots, I guess?)

**Comment by nkshirsagar** [comment]
I started looking into this, and saw that there's already a hotsos check for "call trace"

kernel:
< ... >

    common:
      stacktrace:
        expr: '.*Call Trace:'
        hint: 'Call'

class KernelLogEventChecks(KernelEventChecksBase):
    def __init__(self):

< ... >
    @EVENTCALLBACKS.callback
    def stacktrace(self, event):
        msg = ("kern.log contains {} stacktraces.". <===
               format(len(event.results)))
        issue = issue_types.KernelError(msg)
        issue_utils.add_issue(issue)

But, I do not see it being hit for a sosreport that contains blocked task messages with call traces, when I tested (https://pastebin.canonical.com/p/z55MzGb8hQ/)

If this issue needs to be implemented, do we simply put an entry in bugs.yaml and point to a generic "A task has been blocked" kind of knowledge article (I could not locate one when I searched our knowledge base).. Or would it be better to have it as an event, and a check in the KernelLogEventChecks class.

**Comment by lathiat** [comment]
I think it makes sense to specifically highlight the hung tasks separately to other backtraces. As they have different causes. We could possibly optimise it more to report all such types and a count of each.

**Comment by dosaboy** [comment]
fwiw i tested the call trace check (with the same kern.log) and it worked for me. You can also test it with test data e.g.

$ ./hotsos.sh tests/unit/fake_data_root/ --kernel --short| grep stacktrace
INFO: analysing sosreport at tests/unit/fake_data_root/  
    - desc: kern.log contains 1 stacktraces.

INFO: see --help for more options

**Comment by dosaboy** [comment]
We now have a [CallTraceManager](https://github.com/canonical/hotsos/blob/6b3ef51cadca25efe0c8d7927041676197ca62b2/hotsos/core/plugins/kernel/kernlog/calltrace.py#L351) that allows you to "register" calltrace types and pull information from them so that e.g. it can used in a scenario check.
