### ISSUE TITLE
[k8s] cri-o plugin timeout

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/hotsos#242]
In some of k8s sosreports, I see following error when hotsos is run.
cri-o is one of the container runtime which is not mandatory to run.

sosreport:
  plugin-timeouts:
    - crio
  potential-issues:
    - desc: sosreport plugin 'crio' has timed out and may have incomplete data
      origin: sosreport.plugin_checks
      type: SOSReportWarning

Probably hotsos should check which container runtime are installed/enabled and then throw timeout warnings accordingly.

Note: CDK uses containerd as runtime by default.

**Comment by dosaboy** [comment]
@hemanthnakkina hey so sosreport plugin is simply reporting which sosreport plugins timed out during the creation of the sosreport (it has no bearing on the hotsos plugins themselves). So in your case it is that the crio [1] plugin timed out. The hotsos plugins themselves will only execute if their plugin_runnable property returns True so we are already covered there.

[1] https://github.com/sosreport/sos/blob/main/sos/report/plugins/crio.py

**Comment by dosaboy** [comment]
based in prev comment i'll close this. please re-open if you think it still needs attention.
