### ISSUE TITLE
Not available on non-x86_64 architectures (ARM64 etc)

### ISSUE THREAD

**Issue by lathiat** [canonical/hotsos#243]
Currently the snap cannot be installed on ARM64 hosts, such as an Ubuntu VM running on a new Apple Silicon Mac.

Launchpad can remote-build open source snaps for various architectures including ARM64. The requirements are documented here: https://snapcraft.io/docs/remote-build

See also: https://snapcraft.io/docs/architectures

We should enable all archictures (including armhf and arm64 but there is no reason not to enable the other architectures) and add launchpad remote-builds as part of the snap release process.

hotsos runs fine from a source directory on arm64.

**Comment by lathiat** [comment]
It's not clear to me how the snap is currently released but if we are not already doing it, it probably makes the most sense to setup the automated Build from Github and then just merge in the architecture list.

If the Build from Github is already in use I can just submit a PR for the new architectures.

If it's not enabled then I can do the hard work there we just need to get permissions setup on the snap store for the wider team including me.

**Comment by xtrusia** [comment]
only adding architectures: [amd64, arm64] and I let it build from github https://github.com/xtrusia/hotsos/blob/main/snap/snapcraft.yaml . i removed confinement field as test.. and hotsos-test is published successfully. not sure this will be working on official hotsos as well

**Comment by dosaboy** [comment]
@xtrusia we now have automated builds so I believe we can try re-enabling arch: all to see if it will work
