### ISSUE TITLE
check cpu scaling_governor for ceph nodes

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#250]
Same as https://github.com/canonical/hotsos/blob/master/defs/scenarios/openstack/system_cpufreq_mode.yaml but for ceph.

**Comment by KellenRenshaw** [comment]
Should we simply make this check "global", instead of predicating on a node type? I suspect that the cases where we *want* a non-"performance" governor are the minority, so throwing up a flag is probably a good idea in general.
