### ISSUE TITLE
Call out PG overdose protection

### ISSUE THREAD

**Issue by hillpd** [canonical/hotsos#264]
Since Luminous [0], Ceph will restrict the number of pgs that can be created per OSD. When this occurs, PGs will present as `activating`  or `creating` and will not progress towards an `active` state.

Example ceph health detail logs:
> [WRN] PENDING_CREATING_PGS: 240609 PGs pending on creation

> pg 104.da8 is activating+degraded+remapped, acting [110,162,130,91,61,33,479,213,256]

> pg 123.277 is stuck inactive for 29m, current state creating+activating, last acting [256,500,35,479,312,297,259,481,67]

Example osd log:
> osd.38 104288 maybe_wait_for_max_pg withhold creation of pg 104.8e6s8: 813 >= 750

Recommendation:
Determine why Ceph is trying to create an absurd number of PGs on a single OSD. Fix that issue, and then temporarily raise the `osd_max_pg_per_osd_hard_ratio` to recover the cluster. This may require OSD restarts to kick the corresponding PG state machines.

[0] https://ceph.io/en/news/blog/2017/new-luminous-pg-overdose-protection/#hard-limit-on-pgs-on-each-osd

**Comment by nkshirsagar** [comment]
@hillpd @pponnuvel Do either of you have a link to a sosreport having this issue? I'd like to use it for verification and testing.

**Comment by pponnuvel** [comment]
@nkshirsagar I checked but we don't have the sosreport from that case - it's been deleted due to GDPR. You can probably work with the message in the description along with
1. https://ceph-users.ceph.narkive.com/TcT0P9zL/slow-requests-blocked-no-rebalancing
2. https://tracker.ceph.com/issues/49693

**Comment by nkshirsagar** [comment]
> @nkshirsagar I checked but we don't have the sosreport from that case - it's been deleted due to GDPR. You can probably work with the message in the description along with
> 
> 1. https://ceph-users.ceph.narkive.com/TcT0P9zL/slow-requests-blocked-no-rebalancing
> 2. https://tracker.ceph.com/issues/49693

Hi @pponnuvel ,

the issue https://tracker.ceph.com/issues/49693 does not contain a message related to PGs pending on creation. The link https://ceph-users.ceph.narkive.com/TcT0P9zL/slow-requests-blocked-no-rebalancing has,

"2018-09-20 09:32:58.851160 mon.dri-ceph01 [WRN] Health check update: 249
PGs pending on creation (PENDING_CREATING_PGS)"

Which I am assuming will be in the mon logs. 
I'll assume this to be in the ceph health detail logs, on the mon node sosreport,
"[WRN] PENDING_CREATING_PGS: 240609 PGs pending on creation"

I will add ceph health detail to the cli helper, 

~~~
            'ceph_health_detail':
                [BinCmd('ceph health detail'),
                 FileCmd('sos_commands/ceph_mon/'
                         'ceph_health_detail')],
            'ceph_health_detail_json_decoded':
                [BinCmd('ceph health detail --format json-pretty',
                        json_decode=True),
                 # sosreport < 4.2
                 FileCmd('sos_commands/ceph/json_output/'
                         'ceph_health_detail_--format_json-pretty',
                         json_decode=True),
                 # sosreport >= 4.2
                 FileCmd('sos_commands/ceph_mon/json_output/'
                         'ceph_health_detail_--format_json-pretty',
                         json_decode=True)],
~~~

An OSD node will contain messages in the osd logs also, like,

osd.38 104288 maybe_wait_for_max_pg withhold creation of pg 104.8e6s8: 813 >= 750

Assuming all this is right, I'm trying to figure out a way to write two scenarios..  

1) catch the message in the mon sos [WRN] PENDING_CREATING_PGS: 240609 PGs pending on creation in "ceph health detail"

2) OSD node scenario to spot the message "osd.38 104288 maybe_wait_for_max_pg withhold creation of pg 104.8e6s8: 813 >= 750"
 in /var/log/ceph/ceph-osd.* on the OSD node. 

Does this seem OK in terms of implementing this check?

**Comment by nkshirsagar** [comment]
@pponnuvel I've sent the draft PR to show the changes for the scenario, the unit test is still pending. I have not tested this as yet, just wanted to get an initial review. I'm not sure where to find a sos to test with (both for the mon and the OSD logs), but can just use the strings from the issue description and add those to an existing sos.
