### ISSUE TITLE
Hotsos testing various scenarios

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical/hotsos#267]
The current Hotsos unit tests use a single tree of simulated data to provide test coverage.

Suggest using an alternative method to allow the insertion of sanitized sosreports that will have hotsos run against them, with defined checks.

This would allow easier importing of test environments based on real world usage.

**Comment by dosaboy** [comment]
I forgot to link my commit https://github.com/canonical/hotsos/commit/7d6f1612944345262fecc665ee4de4c0350c9fa9 to this issue but i recently landed support for having per-plugin fake DATA_ROOTs and we now have one for openstack, rabbitmq, kubernetes, ceph-mon, and vault. The rest of the plugins still default to the openstack fake data_root but that can easily be changed. It took some work to get all the unit tests adjusted but its all landed now so please take a look. I'll go ahead and close this issue, please re-open it if you have more suggestions.
