### ISSUE TITLE
detect LP 1874719 - Use the hostname as the node name instead of hardcoded 'node1'

### ISSUE THREAD

**Issue by nicolasbock** [canonical/hotsos#296]
Check for [LP: 1874719] (https://bugs.launchpad.net/charm-hacluster/+bug/1874719).

**Comment by dnegreira** [comment]
@nicolasbock cool! can you assign it to me? Can't seem to be able to self-assign at this point

**Comment by nicolasbock** [comment]
Done :)

**Comment by nicolasbock** [comment]
When you push a PR don't forget to mention or link this issue @dnegreira . That will move this issue into the in progress column of our project board. Thanks again!
