### ISSUE TITLE
Check if openvswitch is restarted after neutron-openvswitch-agent

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/hotsos#331]
Restart of openvswitch without restart of neutron-openvswitch-agent can cause inconsistent l2pop flows [1].
This issue is not resolved upstream.

Need a check in hotsos if openvswitch is restarted after neutron-openvswitch-agent

[1] https://bugs.launchpad.net/neutron/+bug/1794991/comments/66

**Comment by hemanthnakkina** [comment]
Following regex will be helpful in capturing the timestamp the openvswitch/neutron-openvswitch-agent are restarted from the file sosreport-<>/sos_commands/systemd/systemctl_status_--all

.* neutron-openvswitch-agent.service - Openstack Neutron .*? since (.*?);
.* ovs-vswitchd.service - Open vSwitch .*? since (.*?);

**Comment by dosaboy** [comment]
This could be somewhat related to https://github.com/canonical/hotsos/issues/249

As discussed I think a fairly clean way to implement this kind of check would be to add a new "started-after" field to the [requires.systemd](https://github.com/canonical/hotsos/blob/e5b4fc0d100a27eaa4c49a66a7f9df3727fdcbe2/hotsos/core/ycheck/__init__.py#L1107) property so we can do e.g.

```
requires:
  systemd:
    neutron-openvswitch-agent:
      started-after: openvswitch-switch
```

**Comment by dosaboy** [comment]
I have implemented the underlying functionality to implement this check here - https://github.com/canonical/hotsos/pull/333
