### ISSUE TITLE
Unit tests failing on jammy

### ISSUE THREAD

**Issue by dnegreira** [canonical/hotsos#339]
Seems that `nose` [stopped working with jammy](https://paste.ubuntu.com/p/4yRVPjNBNc/).

Since `nose` [is now on maintenance mode for years](https://nose.readthedocs.io/en/latest/) and it breaks with python3.10, I believe we should be looking into other alternatives for unit testing.

Shall we go to `nose2` ? Any other idea/alternative?

**Comment by dosaboy** [comment]
[stestr](https://github.com/mtreinish/stestr) might be a good alternative, it;s what openstack uses
