### ISSUE TITLE
Extend ovn analysis

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#349]
Some ideas of things to add for better ovs/ovn analysis

* identify BFD flapping and report if a port has > 5 in 24 hour period.
* include BFD info in summary
* include tunnel ports/endpoints in summary

**Comment by dosaboy** [comment]
add some of these as needed (we already have external-ids):

```
# ovs-vsctl list open .
_uuid               : a223aec6-7cad-4fe2-bec3-9640336943fd
bridges             : [58f06bc5-588f-45d6-b693-084467cc633d, 5e6bfdae-4266-44ff-ae78-67d60469199b, 7a8c8ef2-f8f9-41a4-a6ff-8cd2974582de]
cur_cfg             : 18
datapath_types      : [netdev, system]
datapaths           : {}
db_version          : "8.2.0"
dpdk_initialized    : false
dpdk_version        : none
external_ids        : {hostname=hertz.segmaas.1ss, ovn-bridge-mappings="physnet1:br-data", ovn-encap-ip="10.230.57.99", ovn-encap-type=geneve, ovn-match-northd-version="true", ovn-remote="ssl:10.230.58.204:6642,ssl:10.230.62.255:6642,ssl:10.230.58.185:6642", rundir="/var/run/openvswitch", system-id=hertz.segmaas.1ss}
iface_types         : [erspan, geneve, gre, internal, ip6erspan, ip6gre, lisp, patch, stt, system, tap, vxlan]
manager_options     : [e8d824d4-080d-41b7-9e7f-b8bba5d2d9a6]
next_cfg            : 18
other_config        : {}
ovs_version         : "2.13.5"
ssl                 : 8b14b33a-ce00-4df7-8ab3-d8c23a14ac64
statistics          : {}
system_type         : ubuntu
system_version      : "20.04"

```

**Comment by aserdean** [comment]
search for `inactivity probe` in `ovs-vswitchd.log`, NB, SB

**Comment by aserdean** [comment]
look at `releasing` and `claiming` of LRP in `ovn-controller.log` if they are flapping more then one time per day signal an issue

**Comment by dosaboy** [comment]
> search for `inactivity probe` in `ovs-vswitchd.log`, NB, SB

we already have this, see https://github.com/canonical/hotsos/blob/main/defs/events/openvswitch/ovn/ovn-central.yaml

**Comment by aserdean** [comment]
true, we still need it for northd and vswitchd though

**Comment by aserdean** [comment]
as an idea, we may correlate with neutron ovsdbapp logs, i.e.:
`clustered database server is not cluster leader; trying another server`
