### ISSUE TITLE
ceph report needs 'first_line_filter'

### ISSUE THREAD

**Issue by pponnuvel** [canonical/hotsos#353]
Some ceph commands have "extra" output in files collected by sosreport (due to stderr being captured) - which makes the json invalid.

We previously have a 'last_line_filter' to workaround it. But it's been observed that this can happen to be the first line as well.

The output was from a old Ceph (mimic), so it could be that what used to first line has now become last line. So this is likely to be an edge case. But a 'first_line_filter' can be implemented to fix it.

**Comment by dosaboy** [comment]
@pponnuvel should we look for the same string at both ends or would it be something different? e.g. for ceph report we look for last_line_filter='report', should just add first_line_filter='report' as well?
