### ISSUE TITLE
Check if juju osd config ceph-cluster-network and ceph-public-network contain multiple ip addresses

### ISSUE THREAD

**Issue by taodd** [canonical/hotsos#363]
Pay attention that if the options ceph-cluster-network and ceph-public-network contains multiple IP addresses
Report a warning if any of the options contains multiple IP addresses.

E.g suppose 10.55.136.0/24  is the public network and 10.55.134.0/24 is the replication network. 
So, we should expect ceph-cluster-network to be '10.55.134.0/24' and ceph-public-network to be '10.55.136.0/24'
if we see a string value like '10.55.136.0/24 10.55.134.0/24' at any of the two options, raise a warning about this that the cluster might have a connectivity issue.

**Comment by dosaboy** [comment]
@taodd we can only observer this if it is in ceph.conf, is that going to be possible?

**Comment by dosaboy** [comment]
ok @taodd confirmed that (a) yes it is observable in ceph.conf and also (b) ceph does actually support using more than one address for each of these configs BUT in this error case the same addresses were used for both cluster/public and we also typically would not expect that to be used. So based on that I think we can define a scenario.
