### ISSUE TITLE
checking charm-mysql-router bug

### ISSUE THREAD

**Issue by xtrusia** [canonical/hotsos#370]
mysql-router < 8.0.23 doesn't support TLS, 
and >= 8.0.23, new option is added ( e.g. client_ssl_mode depends on client_ssl_cert )

latest charm has an issue as it inserts client_ssl_mode forcely without checking if there is client_ssl_cert

so, if mysql-router is upgraded from < 8.0.23 to >= 8.0.23, and charm is upgraded to latest, there will be an error.
(as mysql-router bootstrapping creates configuration file, upgraded mysql-router from < 8.0.23 doesn't have proper client_ssl_cert but charm think it is there )

fixing charm is in progress 

##update

Please refer to LP bug[1]

Thanks.

[1] https://bugs.launchpad.net/charm-mysql-router/+bug/1959861

**Comment by dosaboy** [comment]
@xtrusia can you provide the LP bug number for the charm and also, if possible, an example log that we could use to detect if we are affected by this issue.

**Comment by xtrusia** [comment]
Actually error msg is this

/var/lib/mysql/mysql-router/log/mysqlrouter.log:2022-07-25 08:25:01 main ERROR [7fdb4b5e6e00] Configuration error: client_ssl_cert must be set, if client_ssl_mode is 'PREFERRED'.

but it is now shown right after charm has issue 'Failed to connect to MySQL'

Above error msg is shown when trying to restart mysql-router inside unit.

so My plan is that to check if there is client_ssl_mode but no client_ssl_cert in /var/lib/mysql/mysql-router/mysqlrouter.conf

**Comment by dosaboy** [comment]
ok sounds good. you can find an example of checking mysql config at https://github.com/canonical/hotsos/blob/main/defs/scenarios/mysql/mysql_connections.yaml for ref
