### ISSUE TITLE
Come up with a way to figure out networking issues across a Ceph cluster

### ISSUE THREAD

**Issue by pponnuvel** [canonical/hotsos#372]
I think something is being worked on to analyse/report network issues (packet drops, etc).

But this is a single sosreport view. I am thinking of something that checks the connectivity across the Ceph cluster.
Something that does:
- pings across nodes
- pings with jumbo frames across nodes
- iperf across nodes
- something else

This can be standalone script that does these (not necessarily a part of hotsos). Just "logging" it here.
I think the magpie charm does something similar. But we'd probably need something that's usable in non-charms deployments too.

We often get problems that very sound like "networking issue" but generally takes longer to test/verify/prove it. The aim here is to make that evaluation faster.

**Comment by sombrafam** [comment]
There's a discussion around this topic going on the probelius project: https://github.com/canonical/probelius/issues/8

**Comment by pponnuvel** [comment]
@sombrafam Thanks. That does cover this.
