### ISSUE TITLE
OSD metadata warning needs revisit

### ISSUE THREAD

**Issue by pponnuvel** [canonical/hotsos#434]
```
ubuntu@juju-180f3e-15-lxd-0:~$ sudo ceph osd df tree
ID   CLASS  WEIGHT     REWEIGHT  SIZE     RAW USE  DATA     OMAP     META      AVAIL    %USE  VAR   PGS  STATUS  TYPE NAME           
 -1         654.96509         -  655 TiB  125 GiB   66 GiB  6.2 MiB    59 GiB  655 TiB  0.02  1.00    -          root default        
-12         218.32169         -  218 TiB   41 GiB   22 GiB  2.8 MiB    19 GiB  218 TiB  0.02  0.98    -              rack AZ1        
-11          43.66434         -   44 TiB  8.0 GiB  4.5 GiB  1.2 MiB   3.5 GiB   44 TiB  0.02  0.96    -                  host node-01
  2    ssd    7.27739   1.00000  7.3 TiB  1.4 GiB  909 MiB    2 KiB   538 MiB  7.3 TiB  0.02  1.02  101      up              osd.2   
  6    ssd    7.27739   1.00000  7.3 TiB  1.2 GiB  855 MiB  1.2 MiB   420 MiB  7.3 TiB  0.02  0.90  114      up              osd.6   
 13    ssd    7.27739   1.00000  7.3 TiB  1.8 GiB  814 MiB    1 KiB  1000 MiB  7.3 TiB  0.02  1.28  105      up              osd.13  
 21    ssd    7.27739   1.00000  7.3 TiB  1.1 GiB  670 MiB    1 KiB   497 MiB  7.3 TiB  0.02  0.82   96      up              osd.21  
 31    ssd    7.27739   1.00000  7.3 TiB  1.2 GiB  716 MiB    1 KiB   549 MiB  7.3 TiB  0.02  0.89   99      up              osd.31  
 43    ssd    7.27739   1.00000  7.3 TiB  1.2 GiB  669 MiB    3 KiB   556 MiB  7.3 TiB  0.02  0.86  103      up              osd.43  
-15          43.66434         -   44 TiB  8.2 GiB  4.5 GiB  1.5 MiB   3.7 GiB   44 TiB  0.02  0.99    -                  host node-04
  4    ssd    7.27739   1.00000  7.3 TiB  1.4 GiB  736 MiB  210 KiB   741 MiB  7.3 TiB  0.02  1.04  111      up              osd.4   
  9    ssd    7.27739   1.00000  7.3 TiB  1.3 GiB  799 MiB   40 KiB   539 MiB  7.3 TiB  0.02  0.94  119      up              osd.9   
 16    ssd    7.27739   1.00000  7.3 TiB  1.3 GiB  652 MiB  273 KiB   650 MiB  7.3 TiB  0.02  0.92  102      up              osd.16  
 25    ssd    7.27739   1.00000  7.3 TiB  1.5 GiB  781 MiB   61 KiB   725 MiB  7.3 TiB  0.02  1.06   95      up              osd.25  
 36    ssd    7.27739   1.00000  7.3 TiB  1.4 GiB  770 MiB  297 KiB   656 MiB  7.3 TiB  0.02  1.00  112      up              osd.36  
 48    ssd    7.27739   1.00000  7.3 TiB  1.4 GiB  888 MiB  661 KiB   505 MiB  7.3 TiB  0.02  0.98  103      up              osd.48  
-21          43.66434         -   44 TiB  8.1 GiB  4.2 GiB    6 KiB   3.9 GiB   44 TiB  0.02  0.97    -                  host node-07
 12    ssd    7.27739   1.00000  7.3 TiB  1.8 GiB  878 MiB    1 KiB   938 MiB  7.3 TiB  0.02  1.28  113      up              osd.12  
 20    ssd    7.27739   1.00000  7.3 TiB  1.2 GiB  839 MiB    1 KiB   381 MiB  7.3 TiB  0.02  0.86  109      up              osd.20  
 30    ssd    7.27739   1.00000  7.3 TiB  1.2 GiB  714 MiB    1 KiB   546 MiB  7.3 TiB  0.02  0.89  107      up              osd.30  
 42    ssd    7.27739   1.00000  7.3 TiB  1.2 GiB  589 MiB    1 KiB   612 MiB  7.3 TiB  0.02  0.85   94      up              osd.42  
 52    ssd    7.27739   1.00000  7.3 TiB  1.4 GiB  610 MiB    1 KiB   810 MiB  7.3 TiB  0.02  1.00   89      up              osd.52  
 61    ssd    7.27739   1.00000  7.3 TiB  1.3 GiB  684 MiB    1 KiB   693 MiB  7.3 TiB  0.02  0.97  100      up              osd.61
[...]
````

In fresh clusters, the majority of the disk use is for the metadata. In the example above, there's ~80% of the use is for metadata which obviously triggers the warning (over the current threshold of 2%). 

I am wondering if we need apply a further limit such as raw size of the metadata is over 2G or something similar.

**Comment by pponnuvel** [comment]
https://pastebin.canonical.com/p/vpZM4swkHt/

**Comment by pponnuvel** [comment]
cc: @hillpd

**Comment by taodd** [comment]
Setting a raw size limit makes sense. 
I've seen the bluefs log size increased over 1TB and causing the OSD crash(not able to restart), 2G is still a very strict limit which could cause false alarm, suggest using something bigger like 64G.

**Comment by lathiat** [comment]
This will be due to the size of the default WAL files. The default settings have max_total_wal_size=1GB and I think you end up with at least 2 x 256MB WAL files in some versions. On Ussuri/Octopus I get 1GB base usage and not ~512MB as shown in Pon's exmaple but those defaults maybe changed between versions and will depend a bit on how much small data/compactions have happened.

I think we could cover off all bases by excluding max_total_wal_size(1GB) of usage from the calculation, or, not throwing the alert unless at least 1GB is used. We could maybe be generous and say 2GB but I'd maybe start with 1GB and see how it goes.

**Comment by taodd** [comment]
I think Pon meant the "meta" column of the "ceph osd df tree", it doesn't just include the write ahead log of the rocksdb, but also other metadata in bluefs, including the bluefs log file.
the problem Pon tries to detect should be originally from this one https://bugs.launchpad.net/ubuntu/+source/ceph/+bug/1914911 ?

**Comment by pponnuvel** [comment]
Yes, Dongdong is right - this is about the meta column. 

From the above cluster, sorting by the meta used (values in KBs):
```
$ jq -j '.nodes[] | select(.id>0) | .kb_used_meta," ",.kb_used,"\n"' osd_df_tree | sort -k1 -rn | head
1030525 1912024
1024382 1858244
974142 1763568
961726 1861216
940862 1572328
930878 1789112
916926 1726760
913982 1797564
910461 1768540
909908 1719640
908093 1751812
907197 1721876
906750 1672180
895358 1762056
890109 1770948
885630 1773092
885118 1704364
882899 1720240
879727 1760420
878069 1672936
874430 1586472
868862 1676748
864702 1608124
851900 1644716
849598 1630904
833282 1607068
831166 1456060
829310 1695320
822333 1539264
819582 1566268
815998 1599032
805950 1538184
776254 1427880
759469 1513416
743298 1543260
740989 1432472
718267 1627400
712190 1530708
709886 1410584
706359 1679752
686270 1429292
682686 1453744
676798 1611004
671830 1461020
667838 1339516
665902 1333784
639542 1295044
629883 1300308
629645 1415656
628669 1463864
627134 1230120
623549 1310212
614333 1558660
607805 1498012
605539 1331292
589693 1316544
589053 1396388
586361 1268696
576340 1347116
566206 1299092
561854 1213928
559422 1290748
555070 1350924
554108 1238696
551549 1482820
547799 1320452
546301 1213544
540286 1144168
535639 1354332
534973 1259744
526398 1330504
517674 1428124
515902 1171176
513909 1255948
510014 1196220
484221 1303612
483134 1282308
478014 1239168
445310 1114908
435646 1152088
430674 1307084
426238 1137044
399230 1118044
389950 1248764
386302 1176448
377405 1010892
277438 941012
221264 939452
212993 972220
```

We can see there are number of metadata usage that are really close to 1G despite the overall usage being under 2G. Unless there are cases where even a 2G metadata (whatever may be the OSD size) utilisation could be an issue, I think 2G lower bound is fine, I think.

Created PR #442 with 2G threshold.

**Comment by taodd** [comment]
@pponnuvel 2G probably makes sense for a relatively empty cluster. But the Meta usage will increase as the data grows. 
  Eg. below is example,  OSD.21 got 6.6GB META usage. 

ID   CLASS  WEIGHT     REWEIGHT  SIZE     RAW USE  DATA     OMAP     META     AVAIL    %USE   VAR   PGS  STATUS  TYPE NAME
 -1         261.97998         -  262 TiB   69 TiB   69 TiB   13 GiB  215 GiB  193 TiB  26.39  1.00    -          root default
 -4          87.32666         -   87 TiB   23 TiB   23 TiB  4.4 GiB   72 GiB   64 TiB  26.39  1.00    -              rack AZ1
-11          43.66333         -   44 TiB   12 TiB   12 TiB  2.7 GiB   37 GiB   31 TiB  27.94  1.06    -                  host compute-server-1
  1    ssd    7.27739   1.00000  7.3 TiB  2.0 TiB  2.0 TiB   15 MiB  6.2 GiB  5.2 TiB  28.09  1.06  109      up              osd.1
  8    ssd    7.27739   1.00000  7.3 TiB  1.8 TiB  1.8 TiB  1.1 GiB  5.7 GiB  5.5 TiB  24.71  0.94  125      up              osd.8
 15    ssd    7.27739   1.00000  7.3 TiB  2.3 TiB  2.3 TiB  1.2 GiB  6.4 GiB  5.0 TiB  31.78  1.20  124      up              osd.15
 21    ssd    7.27739   1.00000  7.3 TiB  2.3 TiB  2.3 TiB   34 MiB  6.6 GiB  5.0 TiB  31.60  1.20  113      up              osd.21
 24    ssd    7.27689   1.00000  7.3 TiB  1.6 TiB  1.6 TiB  323 MiB  5.7 GiB  5.7 TiB  21.97  0.83  119      up              osd.24
 25    ssd    7.27689   1.00000  7.3 TiB  2.1 TiB  2.1 TiB  8.8 MiB  6.5 GiB  5.1 TiB  29.47  1.12  120      up              osd.25
 -3          43.66333         -   44 TiB   11 TiB   11 TiB  1.8 GiB   35 GiB   33 TiB  24.83  0.94    -                  host compute-server-4
  0    ssd    7.27739   1.00000  7.3 TiB  1.8 TiB  1.8 TiB  641 MiB  5.8 GiB  5.5 TiB  25.08  0.95  112      up              osd.0
  6    ssd    7.27739   1.00000  7.3 TiB  1.7 TiB  1.7 TiB  739 MiB  5.5 GiB  5.6 TiB  23.01  0.87  109      up              osd.6
 12    ssd    7.27739   1.00000  7.3 TiB  1.6 TiB  1.6 TiB  9.0 MiB  5.5 GiB  5.7 TiB  21.94  0.83  108      up              osd.12
 18    ssd    7.27739   1.00000  7.3 TiB  1.9 TiB  1.9 TiB  401 MiB  6.0 GiB  5.3 TiB  26.77  1.01  118      up              osd.18
 26    ssd    7.27689   1.00000  7.3 TiB  1.9 TiB  1.9 TiB   11 MiB  5.9 GiB  5.4 TiB  25.93  0.98  119      up              osd.26
 27    ssd    7.27689   1.00000  7.3 TiB  1.9 TiB  1.9 TiB   10 MiB  6.1 GiB  5.4 TiB  26.27  1.00  117      up              osd.27


So if this check is not just for the empty cluster (e.g fresh deployed), then 2G is too small. 
A more sophisticated way to do this would require us to:
a. Calculate  the number of total objects on each OSD (this can be done by parsing both ceph_pg_dump and ceph_osd_df_tree)
b. Figure out how much MEATA usage is required for an object on average.  
c. Figure out the normal internal META usages that are not for the object's metadata. 
If the value we see is way more than a *b + c, then we should report a warning. 

But if we just choose a fixed value based on experience, I suggest choosing a bigger one.

**Comment by pponnuvel** [comment]
@taodd 2G is just the lower limit (if it's less than that, we ignore it. As it noted previously, even in relatively empty clusters, it could quickly get up to 1G) - it's not a hard limit.

For larger clusters (with larger meta), it's currently checked whether the meta utilisation is 5% of the overall disk utilisation which was producing false positives in relatively empty clusters. Taking an example from https://github.com/canonical/hotsos/issues/434#issuecomment-1279466170 the meta usage is 1G whereas the total OSD utilisation is only 1.8G - that's nearly 54% (1030525/1912024) metadata so hotsos currently thinks it's really bad but it isn't.
