### ISSUE TITLE
Check TCP/UDP used page count against allowed maximum (/net/ipv4/{udp,tcp}_mem)

### ISSUE THREAD

**Issue by mustafakemalgilor** [canonical/hotsos#445]
At any given time, an absolute maximum number of pages is allowed by the kernel for all TCP/UDP sockets. This value is kept in `net.ipv4.{tcp,udp}_mem` sysctl settings and automatically set at boot time (depending on available system memory).

The `*_mem` value is a three-value vector, consisting of `min, pressure`, and `max` values. If the number of pages allocated for {tcp,udp} reaches to the `max` value, the kernel will start to drop frames.

The number of allocated pages for TCP/UDP at any given time can be observed on the relevant line in `/proc/net/sockstat` file:

``` 
sockets: used 1488
TCP: inuse 36 orphan 0 tw 1 alloc 99 mem 7
UDP: inuse 53 mem 47
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

The `mem` value in each line indicates the number of pages allocated for each protocol. So, in theory, we can compare the actual value against the maximum value to issue a warning (e.g. %85 of allowed pages are reached for UDP). 

This would allow us to notice some problematic scenarios such as: 

- An application that could not keep up with the load
- A resource leak in the kernel

Another take on this might be trying to correlate the actual memory used by all active sockets to the number of total pages used by TCP/UDP sockets. For TCP and UDP, all alive sockets are available under `/proc/net/{tcp,udp}`, together with their respective TX & RX queue sizes, which may help us to estimate how much space all the sockets are occupying at any given moment.

**Comment by mustafakemalgilor** [comment]
Hi @sombrafam ;

Of course, let's look at a concrete example from a host we suspect that have some kind of memory leak:

```text
sockets: used 908
TCP: inuse 22 orphan 0 tw 2 alloc 58 mem 15
UDP: inuse 18 mem 762066
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

Right of the bat, we could tell that something is not right with UDP memory usage, since there are 18 active sockets and `762066` pages of memory used for them. Let's look at the `sysctl` settings for UDP to make sense of it:

```
                   #min   #press  #max
net.ipv4.udp_mem = 381033 508045 762066 #unit: pages
net.ipv4.udp_rmem_min = 4096   #unit: bytes
net.ipv4.udp_wmem_min = 4096   #unit: bytes
net.core.rmem_default = 212992 #unit: bytes
net.core.rmem_max = 212992     #unit: bytes
net.core.wmem_default = 212992 #unit: bytes
net.core.wmem_max = 212992     #unit: bytes
``` 

Here, we can see that the maximum number of pages allowed for UDP is `762066`, and the system has exhausted all of them. So, either the sockets are using these pages by normal means (e.g. allocated receive/send buffers) or there is a leak. Given that there are 18 active sockets and rmem_max/wmem_max is configured to 52 pages, we should see (52 * 2) * 18 = ~1872 pages of memory in use approximately. But this is not the scenario, so either there is something we didn't account for or a memory leak.

We can also peek into `proc/net/udp` to see tx/rx queues per socket:

```
   sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode ref pointer drops            
   33: FFFFFFFF:CCCC FFFFFFFF:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33101903 2 ffffa08167a9fc00 1      
  100: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33100045 2 ffffa07ff6ba6000 1      
  346: FFFFFFFF:CCCC DDDDDDDD:BBBB 07 00000000:00000000 00:00000000 00000000   100        0 23615 2 ffffa08166988400 2         
  558: FFFFFFFF:CCCC DDDDDDDD:BBBB 07 00000000:00000000 00:00000000 00000000     0        0 96393 2 ffffa08164ec6400 0         
  601: FFFFFFFF:CCCC DDDDDDDD:BBBB 07 00000000:00000000 00:00000000 00000000     0        0 21120 2 ffffa08167136000 0         
  924: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33101976 2 ffffa08167a9e400 1      
 1145: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33100889 2 ffffa081684f0c00 1      
 1253: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33100015 2 ffffa07ff6ba7000 1      
 2207: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33101897 2 ffffa08167a9f400 1      
 2779: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33098018 2 ffffa07ff6a71400 1      
 3070: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33100888 2 ffffa081684f3400 1      
 3354: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33101910 2 ffffa08167a9e000 1      
 4938: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33099748 2 ffffa081684f0400 1      
 5402: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33101977 2 ffffa08167a9f000 1      
 6638: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33098017 2 ffffa07ff6a71000 1      
 7002: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33100036 2 ffffa07ff6ba7400 1      
 7166: FFFFFFFF:CCCC DDDDDDDD:BBBB 07 00000000:00000000 00:00000000 00000000     0        0 33095364 2 ffffa07e80a1b000 1      
 7367: FFFFFFFF:CCCC DDDDDDDD:BBBB 01 00000000:00000000 00:00000000 00000000     0        0 33099908 2 ffffa07ff6ba7c00 1 

```
We can see that the TX/RX queues of sockets are empty, so there should be no reason that UDP sockets should occupy these many pages, hence we probably have a leak.

**Comment by sombrafam** [comment]
Thanks for the detailed explanation!
