### ISSUE TITLE
snap broken

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#469]
The changes in patch https://github.com/canonical/hotsos/commit/366b8f02a0de107e6658d47cb6b312bb004e9617 seem to have somehow broken the snap and I get the following after upgrade:

$ hotsos
cannot snap-exec: cannot exec "/snap/hotsos/600/bin/hotsos": no such file or directory

I will revert the patch for now and build a new snap.

**Comment by nicolasbock** [comment]
What OS did you run this snap on? Do you still have the snap binary?

**Comment by dosaboy** [comment]
I'm running on Ubuntu Jammy 22.04, snap version is 600 and it should still be possible to install it from edge.
