### ISSUE TITLE
[ceph] Detect full pools

### ISSUE THREAD

**Issue by nkshirsagar** [canonical/hotsos#474]
Detect this kind of a situation with ceph, where pools are reported full

~~~  cluster:
    id:     64g63r6-f6d3-1527-91f5-47g15f2b10d4
    health: HEALTH_ERR
          1 full osd(s)
          13 pool(s) full
~~~

**Comment by pponnuvel** [comment]
Not sure reporting on full OSDs are that useful because it should already be obvious as the cluster won't be fully functional (read-only pools, HEALTH_ERROR status, etc).

See https://github.com/canonical/hotsos/issues/216 for a similar one.

**Comment by nkshirsagar** [comment]
Closing this, as the status will be updated in ceph health detail and flagged already by hotsos since it wont be a normal status
