### ISSUE TITLE
OSD is not able to cache onodes

### ISSUE THREAD

**Issue by taodd** [canonical/hotsos#480]
Details are at [1]
one is to check below osd log:

"2022-10-25T00:47:26.562+0000 7f424f78e700 30 bluestore.MempoolThread(0x564a9dae2a68) _resize_shards max_shard_onodes: 0 max_shard_buffer: 8388608"

If the max_shard_onodes is 0, this needs to be flagged and strongly indicating it might causing the bug above. 

Another way is checking (if the dump_mempool is available) if the onode number is very small
Like below:

"bluestore_cache_onode": {
"items": 3,
"bytes": 1848
},

We should flag when the onode's number is less than 100

[1] https://bugs.launchpad.net/ubuntu/+source/ceph/+bug/1996010

**Comment by pponnuvel** [comment]
An example dump_mempool at `/customers/bloomberg/00345802/ceph-mempools-after.tar.xz`
