### ISSUE TITLE
Checking MAAS proxy doesn't work with TAG_NONE/503 0 CONNECT

### ISSUE THREAD

**Issue by xtrusia** [canonical/hotsos#482]
I saw a customer's symptom that maas-proxy doesn't work with TAG_NONE/503 0 CONNECT

in this case,

forward_max_tries 50 to maas-proxy.conf would be helpful.

on MAAS host ( which has maas-proxy )
/var/log/maas/proxy/access.log

1666854189.800     68 xx.xx.xx.xx. TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.40 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.61 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.65 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.58 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.31 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.50 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.60 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.68 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.253 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.82 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.80 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.192 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.60 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.7 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.48 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.26 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.225 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.62 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.114 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.41 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.158 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.226 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.39 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -
1666854189.800     68 xx.xx.xx.235 TAG_NONE/503 0 CONNECT api.snapcraft.io:443 - HIER_NONE/- -

**Comment by dosaboy** [comment]
@xtrusia is there a log or something that we can use to detect the problem?

**Comment by xtrusia** [comment]
> 

yes, I updated description.

**Comment by xtrusia** [comment]
I think sosreport doesn't collect MAAS maas-proxy.log installed by snap ?

**Comment by dosaboy** [comment]
Is this really an indication of high load on the proxy side or is it that the destination (api.snapcraft.io:443) is not responding fast enough?
