### ISSUE TITLE
warn if lxcfs-libfuse is running out of worker threads (case 00351979)

### ISSUE THREAD

**Issue by nkshirsagar** [canonical/hotsos#512]
Logs like 

Jan 05 00:00:11 ic-hrvart4-s4anq599 lxd.daemon[5447]: fuse: error creating thread: Resource temporarily unavailable

are seen in journal logs.

This is an lxcfs deadlock and often leads to this libfuse deadlock (https://github.com/lxc/lxcfs/issues/471) 

The lxcfs deadlock is introduced in lxd snap version 5.9 through https://github.com/lxc/lxcfs/commit/54db3e71b80fb8a25c9d6bd8ae9be0f0b4b41f26 , and fixed through https://github.com/lxc/lxcfs/pull/579 (if the lxd snap is used it bundles lxcfs in it) in lxd snap version 5.10 (5.10-b392610)

**Comment by joalif** [comment]
Hotsos warns about this buig by checking the lxd version.
For more information take a look [here](https://github.com/canonical/hotsos/pull/523/commits/fc0845c052e5048afa9f2d66ae7a06354b2fc552).

**Comment by nkshirsagar** [comment]
@joalif https://github.com/canonical/hotsos/pull/523/commits/fc0845c052e5048afa9f2d66ae7a06354b2fc552 seems to detect vulnerability to the deadlock, not the deadlock itself. Do you think this makes for an additional check, whether they're actually hit the out of resource condition?
