### ISSUE TITLE
Detect fake full OSDs

### ISSUE THREAD

**Issue by taodd** [canonical/hotsos#513]
From the output of "ceph osd df tree" command, there is a RAW usage column and a DATA usage column.
Below OSD.123 is an example that the DATA usage is only about 2.0TB, but it falsely claimed to consume 6.6TB RAW space. 
The workaround is a restart of that problematic OSD.

66    ssd    6.98630   1.00000  7.0 TiB  264 GiB  263 GiB    83 MiB  1.1 GiB  6.7 TiB   3.69  0.06   53      up              osd.66
 76    ssd    6.98630   1.00000  7.0 TiB  844 GiB  843 GiB   6.4 MiB  1.8 GiB  6.2 TiB  11.80  0.19   50      up              osd.76
123    ssd    3.50000   0.25000  7.0 TiB  6.6 TiB  2.0 TiB    38 MiB  7.7 GiB  362 GiB  94.94  1.57   44      up              osd.123
127    ssd    6.98630   1.00000  7.0 TiB  1.6 TiB  1.6 TiB   8.8 MiB  2.9 GiB  5.4 TiB  22.38  0.37   54      up              osd.127
129    ssd    6.98630   1.00000  7.0 TiB  3.8 TiB  3.8 TiB    35 MiB  9.7 GiB  3.2 TiB  54.49  0.90  112      up              osd.129
131    ssd    6.98630   0.89999  7.0 TiB  4.4 TiB  4.3 TiB    15 MiB   11 GiB  2.6 TiB  62.34  1.03  116      up              osd.131

**Comment by pponnuvel** [comment]
I am kind of wondering whether this issue still afflicts Daimler. Do we have an upstream bug to track this?
