### ISSUE TITLE
Warn if rgw frontend isn't beast

### ISSUE THREAD

**Issue by pponnuvel** [canonical/hotsos#537]
Check `rgw_frontends` and if it's not beast issue a warning.

The older one is civetweb and is no longer supported (except if they're using older Ceph .e.g Luminous). Beast is the default since Nautilus.

So `if Ceph_major_version >= 14 && rgw_frontends != beast` issue a warning that beast should used.

**Comment by hillpd** [comment]
A couple of quick notes:
- The beast frontend was added in Mimic and made default in Nautilus. 
- The civetweb frontend was completely removed in Pacific.
- Old revisions of charm-ceph-radosgw hardcode civetweb as the frontend in `ceph.conf`. 
- [LP#1865396](https://bugs.launchpad.net/charm-ceph-radosgw/+bug/1865396) added charm support for the beast frontend.

Recent charms will set beast as default on Octopus or later. If this warning occurs, we generally should recommend a charm-ceph-radosgw upgrade.
