### ISSUE TITLE
cross check that ovn-meta-<network-uuid> ns exists for all vm guest networks

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#568]
On a compute host running neutron-ovn-metadata-agent, all networks used by running vms should have an associated ovn-meta-<uuid> namespace since if they do not the vms will not be able to reach their metadata, dhcp etc.

**Comment by tpsilva** [comment]
Info not available on sosreport. Closing this issue as discussed, @dosaboy.

**Comment by dosaboy** [comment]
well actually the info just isn't available at all. the issue was opened on the basis that we could get neutron network info from libvirt but actually it isnt there so there is nothing to cross-reference with namespace uuids.
