### ISSUE TITLE
Verification for CPU configuration on neutron ovs dpdk based computes

### ISSUE THREAD

**Issue by nishant-dash** [canonical/hotsos#636]
We should have a check to verify that lcore cpu-set, pmd cpu-set, cpu affinity and nova cpu-sets do not overlap. 

Based of [1] and [2]

[1] https://bugs.launchpad.net/charm-ovn-chassis/+bug/1905416
[2] https://bugs.launchpad.net/juju-lint/+bug/2023562

**Comment by dosaboy** [comment]
this feels similar to the logic in https://github.com/canonical/hotsos/blob/main/hotsos/defs/scenarios/openstack/nova/cpu_pinning.yaml perhaps we can extend that cover this scenario

**Comment by peppepetra** [comment]
The cpu sets we are interested to extend that logic are:

data-path cores (PMD threads):
```
ovs-appctl dpif-netdev/pmd-stats-show | grep core_id
```

non data-path cores (Lcores)
```
ovs-appctl dpdk/lcore-list
```

Especially for pmd threads, having overlap with cpu-affinity and/or nova-compute cpu-{shared|dedicated}-set will cause major issues to the VMs and to OpenvSwitch itself.

PMD threads need a minimum of 1 core per numa node. Ideally in Hosts with SMT (Hyper-threading), pmd threads should get 2 cores per Numa, to get both the two siblings associated with the same physical core.
