### ISSUE TITLE
ovn-northd memory usage isn't accurately reported by hotsos

### ISSUE THREAD

**Issue by nishant-dash** [canonical/hotsos#675]
When I run hotsos with the openvswitch plugin on an ovn-central node on focal, I see
```console
    OpenvSwitchWarnings:
      - The ovn-northd service is consuming more than 5G memory (current=903585792).
        This is not normal and could indicate a memory leak. Please check. (origin=openvswitch.auto_scenario_check
```

However,  when checking
```console
root     1940327  3.6  0.0 5653052 850368 ?      Ssl  Apr13 4679:30 ovn-northd -vconsole:emer -vsyslog:err -vfile:info --ovnnb-db=ssl:10.130.11.131:6641,ssl:10.130.12.66:6641,ssl:10.130.13.120:6641 --ovnsb-db=ssl:10.130.11.131:16642,ssl:10.130.12.66:16642,ssl:10.130.13.120:16642 -c /etc/ovn/cert_host -C /etc/ovn/ovn-central.crt -p /etc/ovn/key_host --no-chdir --log-file=/var/log/ovn/ovn-northd.log --pidfile=/var/run/ovn/ovn-northd.pid --detac
```

that is only a RSS of 850 MB. 

Also It would be nice if hotsos directly reported the units beside `current=XXX <units>`

Env:
- Ubuntu 20.04.4 LTS
- in a lxd
- ovn-central unit, 22.03 on openstack focal ussuri
- hotsos(deb): 1.15.10.g4b8e03649057+20.04.20230707194707

**Comment by mustafakemalgilor** [comment]
It seems that the value is currently retrieved from the respective systemd services' memory cgroup:

https://github.com/canonical/hotsos/blob/4b8e036490572a63d692f67fd100f1518734389a/hotsos/core/host_helpers/systemd.py#L56-L61

The memory consumption is being pulled from the `memory.usage_in_bytes` (or `memory.current` if >=jammy). The [kernel cgroup documentation](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt) mentions that `memory.usage_in_bytes` does not reflect the exact memory usage and it's better to rely on (RSS + CACHE + SWAP) instead:

```text
5.5 usage_in_bytes

For efficiency, as other kernel components, memory cgroup uses some optimization
to avoid unnecessary cacheline false sharing. usage_in_bytes is affected by the
method and doesn't show 'exact' value of memory (and swap) usage, it's a fuzz
value for efficient access. (Of course, when necessary, it's synchronized.)
If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP)
value in memory.stat(see 5.2).
```

**Comment by dosaboy** [comment]
i also realised that the number i had added to represent 5G in the scenarios was wrong :/ so ive fixed that also
