### ISSUE TITLE
changing the journalctl log collection with  -o with-unit as default

### ISSUE THREAD

**Issue by arif-ali** [canonical/hotsos#717]
In sos project there is a current PR sosreport/sos#3346 that may cause issues in interpretation and analysis of logs.

This issue has been created to see if this is indeed the case and have discussion around this

**Comment by dosaboy** [comment]
as I understand it the above pull request affects the "logs" plugin output which is a text representation of the journal itself (which is also included in sosreports). We (hotsos) do not use the logs plugin at all and instead make queries on the journal itself so I don't believe the above PR affects us.

**Comment by arif-ali** [comment]
Thanks @dosaboy, will close this one off
