### ISSUE TITLE
Spinner does not work when hotsos run on tar file

### ISSUE THREAD

**Issue by brianphaley** [canonical/hotsos#729]
Hotsos now has support for running directly on a tar file, but it's "spinner" code doesn't work, looks something like this in an 80-column window:

-> hotsos sosreport-juju-1cb930-51-lxd-18-00368438-2023-09-20-lowcoqa.tar.xz
INFO: extracting sosreport sosreport-juju-1cb930-51-lxd-18-00368438-2023-09-20-lowcoqa.tar.xz to /var/tmp/tmp1pboi7vt/sosreport-juju-1cb930-51-lxd-18-00368438-2023-09-20-lowcoqa
INFO: analysing sosreport /var/tmp/tmp1pboi7vt/sosreport-juju-1cb930-51-lxd-18-0
INFO: analysing sosreport /var/tmp/tmp1pboi7vt/sosreport-juju-1cb930-51-lxd-18-0
INFO: analysing sosreport /var/tmp/tmp1pboi7vt/sosreport-juju-1cb930-51-lxd-18-0
(repeated a gazillion times)
INFO: analysing sosreport /var/tmp/tmp1pboi7vt/sosreport-juju-1cb930-51-lxd-18-0
INFO: analysing sosreport /var/tmp/tmp1pboi7vt/sosreport-juju-1cb930-51-lxd-18-0
INFO: analysing sosreport /var/tmp/tmp1pboi7vt/sosreport-juju-1cb930-51-lxd-18-00368438-2023-09-20-lowcoqa |
hotsos:
  version: 1.16.1.post8
  repo-info: cd3edffd
...

I tried on another system to make sure it wasn't something in my environment.

Extracting and running on the resultant directory works fine for the same report.

**Comment by dosaboy** [comment]
i get the same if my terminal size is smaller than the line length but that's because the spinner is at the end of the line

**Comment by brianphaley** [comment]
Right, it's my old-fashioned 80-column terminal. I think we can change this to print the file/dir name on its own line, followed by a short "analysing" statement.
