### ISSUE TITLE
Auto-deduced YAML test case names collide when the file name includes more than one dot 

### ISSUE THREAD

**Issue by mustafakemalgilor** [canonical/hotsos#818]
Assuming the following YAML file names, the auto-deduced test case names are the same even though the file names are different:

- lp1896125-17.0.0.yaml
- lp1896125-17.0.1.yaml

These files yield `lp1896125-17` as the test name, which leads to a name collision.

Ideally, the code should strip away the file extension, sanitize the remainder, and use that as a test name.

**Comment by dosaboy** [comment]
@mustafakemalgilor while we should probably fix that, I feel it makes sense to give the files meaningful names so that you can tell what they are doing from their name so e.g. suffix like _pass.yaml _fail.yaml is what i usually use.

**Comment by mustafakemalgilor** [comment]
Sure, in this context the suffixes are version numbers for different keystone releases I'd like to test the scenario against. I wanted to be verbose on test cases for ensuring that the new version comparison logic works as intended for non-superficial use cases.
